città:
        - "musica/city1.mp3"
        - "musica/city2.mp3"
        
battaglia:
        - "musica/battaglia1.mp3"
        - "musica/battaglia2.mp3"
        - "musica/battaglia3.mp3"

taverna:
        - "musica/taverna1.mp3"
        - "musica/taverna2.mp3"
	
mare:
        - "musica/mare1.mp3"
        - "musica/mare2.mp3"
        
foresta:
        - "musica/foresta1.mp3"

caverna:
        - "musica/caverna1.mp3"

villaggio_isola:
        - "musica/villaggio_isola1.mp3"

        

    
