#+TITLE: Waterdeep
#+AUTHOR: Mario Calcagno

Waterdeep, conosciuta anche come la *Città degli Splendori* o la *Corona*
*del Nord*, è la città più importante ed influente del Nord, e forse di
tutto il Faerûn. La strada per Waterdeep è ben asfaltata e ben
pattugliata. La città è il fulcro del commercio dalle terre ricche di
minerali a nord, dei regni mercantili a sud, dei regni del mare
interno a est e dei regni e commercianti del mare a ovest.

Si sviluppa sul mare a nord, estendendosi lungo i fianchi del Monte
Waterdeep, che ospita il clan nanico di Melairkyn. La grande
profondità della montagna è rappresentata dal Sottomonte, un luogo
pieno di ricchezze. Proprio per questo, è obiettivo comune per
avventurieri che godono della vicinanza delle principali taverne, come
la famosa taverna Il Portale Sbadigliante, e templi della città.

Waterdeep fu costruita sul sito dell’antico insediamento elfico di
Aelinthaldaar, che lasciò il posto a una comunità agricola di umani,
chiamando la città “Tenuta di Nimoar”. Il nome “Waterdeep” era usato
dai capitani delle navi che attraccavano per commerciare, in quanto il
suo porto naturale è sempre stato caratterizzato da acque profonde. Fu
così che il nome fu lentamente adottato nell’uso comune.

La città è il più grande porto magico del Faerûn. Sebbene accolga
favorevolmente la maggior parte delle razze spaziali, le leggi di
Waterdeep richiedono che tutte le navi atterrino a diverse miglia
dalla costa per poi avvicinarsi via mare al porto. I trasgressori
vengono puniti con pesanti sanzioni. Questa regola, che vale anche per
le navi in partenza, è stata applicata per evitare il panico di massa
della popolazione all’arrivo di una nave extra planare.
